export const LAYOUT_CONSTANTS = {
	BLOCK_VERTICAL_SPACING: 45,
	BLOCK_VERTICAL_SPACING_OFFSET: 0,
	CONNECTION_ELEMENT_WIDTH: 40,
	CONNECTION_ELEMENT_HEIGHT: 20,
	DRAGGING_Z_INDEX: 1000,
	INPUT_HEIGHT: 25,
	INPUT_PADDING: 6,
	INPUT_BORDER_RADIUS: 9999,
	BLOCK_MIN_WIDTH: 150,
	BLOCK_MIN_HEIGHT: 60,
	BLOCK_PADDING: 20,
	VALUE_BLOCK_MIN_HEIGHT: 36,
	LOOP_BLOCK_CLOSE_HEIGHT: 20
} as const;

export const CANVAS_CONSTANTS = {
	DEFAULT_WIDTH: 2000,
	DEFAULT_HEIGHT: 2000,
	GRID_SIZE: 20
} as const;

export const SELECTOR_CONSTANTS = {
	SIDEBAR_ID: '#sidebar',
	BLOCK_DATA_ATTRIBUTE: 'data-block-id',
	INPUT_DATA_ATTRIBUTE: 'data-input-id',
	OUTPUT_DATA_ATTRIBUTE: 'data-output-id',
	LOOP_DATA_ATTRIBUTE: 'data-loop-id'
} as const;
