/**
 * アプリケーション全体で使用されるエラーコード定数
 */
export const ERROR_CODES = {
	// ブロック関連エラー
	BLOCK: {
		NOT_FOUND: 'BLOCK_NOT_FOUND',
		INVALID_TYPE: 'BLOCK_INVALID_TYPE',
		INVALID_POSITION: 'BLOCK_INVALID_POSITION',
		CONNECTION_FAILED: 'BLOCK_CONNECTION_FAILED',
		CIRCULAR_DEPENDENCY: 'BLOCK_CIRCULAR_DEPENDENCY',
		MAX_CONNECTIONS_EXCEEDED: 'BLOCK_MAX_CONNECTIONS_EXCEEDED',
		CREATION_FAILED: 'BLOCK_CREATION_FAILED',
		UPDATE_FAILED: 'BLOCK_UPDATE_FAILED',
		DELETE_FAILED: 'BLOCK_DELETE_FAILED',
		CALCULATION_FAILED: 'BLOCK_CALCULATION_FAILED',
		INTERACTION_FAILED: 'BLOCK_INTERACTION_FAILED'
	},

	// キャンバス関連エラー
	CANVAS: {
		INVALID_VIEWPORT: 'CANVAS_INVALID_VIEWPORT',
		COORDINATE_CONVERSION_FAILED: 'CANVAS_COORDINATE_CONVERSION_FAILED',
		RENDERING_FAILED: 'CANVAS_RENDERING_FAILED',
		ZOOM_OUT_OF_BOUNDS: 'CANVAS_ZOOM_OUT_OF_BOUNDS',
		VIEWPORT_UPDATE_FAILED: 'CANVAS_VIEWPORT_UPDATE_FAILED'
	},

	// ドラッグ&ドロップ関連エラー
	DRAG: {
		INVALID_BLOCK: 'DRAG_INVALID_BLOCK',
		DROP_TARGET_INVALID: 'DRAG_DROP_TARGET_INVALID',
		DRAG_START_FAILED: 'DRAG_START_FAILED',
		DRAG_UPDATE_FAILED: 'DRAG_UPDATE_FAILED',
		DROP_FAILED: 'DRAG_DROP_FAILED',
		SNAP_CALCULATION_FAILED: 'DRAG_SNAP_CALCULATION_FAILED'
	},

	// プロジェクト関連エラー
	PROJECT: {
		SAVE_FAILED: 'PROJECT_SAVE_FAILED',
		LOAD_FAILED: 'PROJECT_LOAD_FAILED',
		INVALID_FORMAT: 'PROJECT_INVALID_FORMAT',
		CORRUPTED_DATA: 'PROJECT_CORRUPTED_DATA',
		PERMISSION_DENIED: 'PROJECT_PERMISSION_DENIED',
		FILE_NOT_FOUND: 'PROJECT_FILE_NOT_FOUND'
	},

	// バリデーション関連エラー
	VALIDATION: {
		REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
		INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
		OUT_OF_RANGE: 'VALIDATION_OUT_OF_RANGE',
		TYPE_MISMATCH: 'VALIDATION_TYPE_MISMATCH'
	},

	// システム関連エラー
	SYSTEM: {
		INITIALIZATION_FAILED: 'SYSTEM_INITIALIZATION_FAILED',
		MEMORY_LIMIT_EXCEEDED: 'SYSTEM_MEMORY_LIMIT_EXCEEDED',
		PERFORMANCE_DEGRADED: 'SYSTEM_PERFORMANCE_DEGRADED',
		UNKNOWN_ERROR: 'SYSTEM_UNKNOWN_ERROR',
		STORE_COMMUNICATION_FAILED: 'SYSTEM_STORE_COMMUNICATION_FAILED'
	}
} as const;

/**
 * エラーコードの型定義
 */
export type ErrorCode =
	| (typeof ERROR_CODES.BLOCK)[keyof typeof ERROR_CODES.BLOCK]
	| (typeof ERROR_CODES.CANVAS)[keyof typeof ERROR_CODES.CANVAS]
	| (typeof ERROR_CODES.DRAG)[keyof typeof ERROR_CODES.DRAG]
	| (typeof ERROR_CODES.PROJECT)[keyof typeof ERROR_CODES.PROJECT]
	| (typeof ERROR_CODES.VALIDATION)[keyof typeof ERROR_CODES.VALIDATION]
	| (typeof ERROR_CODES.SYSTEM)[keyof typeof ERROR_CODES.SYSTEM];
