name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { os: ubuntu-latest,  target: linux }  # deb, appimage
          - { os: macos-latest,  target: macos }  # dmg
          - { os: windows-latest, target: windows } # msi
    runs-on: ${{ matrix.platform.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node (bun)
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install frontend deps
        run: bun install --frozen-lockfile

      - name: Build (Tauri)
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: |
          bun run build
          npx tauri build --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-bundles-${{ matrix.platform.target }}
          path: src-tauri/target/release/bundle

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Generate latest.json (placeholder)
        run: |
          echo '{"version":"'${GITHUB_REF_NAME#v}'","notes":"Auto release","pub_date":"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' > latest.json
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            latest.json
            dist/**/**
